export enum TicketHistoryAction {
  TICKET_CREATED = "TICKET_CREATED",
  PRIORITY_CHANGED = "PRIORITY_CHANGED",
  ASSIGNED = "ASSIGNED",
  STATUS_CHANGED = "STATUS_CHANGED",
  CATEGORY_CHANGED = "CATEGORY_CHANGED",
  COMMENT_ADDED = "COMMENT_ADDED",
}
